name: CI
permissions:
  contents: read

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify formatting
        run: |
          fmt_output=$(gofmt -l .)
          if [ -n "$fmt_output" ]; then
            echo "The following files need gofmt:" && echo "$fmt_output"
            exit 1
          fi

      - name: Run tests
        run: go test ./...

      - name: Build .deb package
        run: make package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: launcher-linux-artifacts
          path: |
            dist/launcher
            dist/*.deb
