name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 0.1.4)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Update version
        run: |
          version="${{ inputs.version }}"
          sed -i "s/^VERSION ?= .*/VERSION ?= ${version}/" Makefile
          git diff --stat

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...

      - name: Build .deb package
        run: make package

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit version bump
        run: |
          if git diff --quiet; then
            echo "No changes detected"
          else
            git commit -am "Release v${{ inputs.version }}"
            git push origin HEAD
          fi

      - name: Create tag
        run: |
          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}

      - name: Publish release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          generate_release_notes: true
          files: |
            dist/launcher
            dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
